/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleAuthenticatedRouteRouteImport } from './routes/$locale/_authenticated/route'
import { Route as LocaleAuthenticatedIndexRouteImport } from './routes/$locale/_authenticated/index'
import { Route as Localeerrors503RouteImport } from './routes/$locale/(errors)/503'
import { Route as Localeerrors500RouteImport } from './routes/$locale/(errors)/500'
import { Route as Localeerrors404RouteImport } from './routes/$locale/(errors)/404'
import { Route as Localeerrors403RouteImport } from './routes/$locale/(errors)/403'
import { Route as Localeerrors401RouteImport } from './routes/$locale/(errors)/401'
import { Route as LocaleauthSignUpRouteImport } from './routes/$locale/(auth)/sign-up'
import { Route as LocaleauthSignIn2RouteImport } from './routes/$locale/(auth)/sign-in-2'
import { Route as LocaleauthSignInRouteImport } from './routes/$locale/(auth)/sign-in'
import { Route as LocaleauthOtpRouteImport } from './routes/$locale/(auth)/otp'
import { Route as LocaleauthForgotPasswordRouteImport } from './routes/$locale/(auth)/forgot-password'
import { Route as LocaleAuthenticatedSettingsRouteRouteImport } from './routes/$locale/_authenticated/settings/route'
import { Route as LocaleAuthenticatedUsersIndexRouteImport } from './routes/$locale/_authenticated/users/index'
import { Route as LocaleAuthenticatedTasksIndexRouteImport } from './routes/$locale/_authenticated/tasks/index'
import { Route as LocaleAuthenticatedSettingsIndexRouteImport } from './routes/$locale/_authenticated/settings/index'
import { Route as LocaleAuthenticatedHelpCenterIndexRouteImport } from './routes/$locale/_authenticated/help-center/index'
import { Route as LocaleAuthenticatedChatsIndexRouteImport } from './routes/$locale/_authenticated/chats/index'
import { Route as LocaleAuthenticatedAppsIndexRouteImport } from './routes/$locale/_authenticated/apps/index'
import { Route as LocaleAuthenticatedSettingsNotificationsRouteImport } from './routes/$locale/_authenticated/settings/notifications'
import { Route as LocaleAuthenticatedSettingsDisplayRouteImport } from './routes/$locale/_authenticated/settings/display'
import { Route as LocaleAuthenticatedSettingsAppearanceRouteImport } from './routes/$locale/_authenticated/settings/appearance'
import { Route as LocaleAuthenticatedSettingsAccountRouteImport } from './routes/$locale/_authenticated/settings/account'
import { Route as LocaleAuthenticatedErrorsErrorRouteImport } from './routes/$locale/_authenticated/errors/$error'

const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleAuthenticatedRouteRoute =
  LocaleAuthenticatedRouteRouteImport.update({
    id: '/_authenticated',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleAuthenticatedIndexRoute =
  LocaleAuthenticatedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocaleAuthenticatedRouteRoute,
  } as any)
const Localeerrors503Route = Localeerrors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const Localeerrors500Route = Localeerrors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const Localeerrors404Route = Localeerrors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const Localeerrors403Route = Localeerrors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const Localeerrors401Route = Localeerrors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleauthSignUpRoute = LocaleauthSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleauthSignIn2Route = LocaleauthSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleauthSignInRoute = LocaleauthSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleauthOtpRoute = LocaleauthOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleauthForgotPasswordRoute =
  LocaleauthForgotPasswordRouteImport.update({
    id: '/(auth)/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleAuthenticatedSettingsRouteRoute =
  LocaleAuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LocaleAuthenticatedRouteRoute,
  } as any)
const LocaleAuthenticatedUsersIndexRoute =
  LocaleAuthenticatedUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => LocaleAuthenticatedRouteRoute,
  } as any)
const LocaleAuthenticatedTasksIndexRoute =
  LocaleAuthenticatedTasksIndexRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => LocaleAuthenticatedRouteRoute,
  } as any)
const LocaleAuthenticatedSettingsIndexRoute =
  LocaleAuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocaleAuthenticatedSettingsRouteRoute,
  } as any)
const LocaleAuthenticatedHelpCenterIndexRoute =
  LocaleAuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => LocaleAuthenticatedRouteRoute,
  } as any)
const LocaleAuthenticatedChatsIndexRoute =
  LocaleAuthenticatedChatsIndexRouteImport.update({
    id: '/chats/',
    path: '/chats/',
    getParentRoute: () => LocaleAuthenticatedRouteRoute,
  } as any)
const LocaleAuthenticatedAppsIndexRoute =
  LocaleAuthenticatedAppsIndexRouteImport.update({
    id: '/apps/',
    path: '/apps/',
    getParentRoute: () => LocaleAuthenticatedRouteRoute,
  } as any)
const LocaleAuthenticatedSettingsNotificationsRoute =
  LocaleAuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => LocaleAuthenticatedSettingsRouteRoute,
  } as any)
const LocaleAuthenticatedSettingsDisplayRoute =
  LocaleAuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => LocaleAuthenticatedSettingsRouteRoute,
  } as any)
const LocaleAuthenticatedSettingsAppearanceRoute =
  LocaleAuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => LocaleAuthenticatedSettingsRouteRoute,
  } as any)
const LocaleAuthenticatedSettingsAccountRoute =
  LocaleAuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => LocaleAuthenticatedSettingsRouteRoute,
  } as any)
const LocaleAuthenticatedErrorsErrorRoute =
  LocaleAuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => LocaleAuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleAuthenticatedRouteRouteWithChildren
  '/$locale/settings': typeof LocaleAuthenticatedSettingsRouteRouteWithChildren
  '/$locale/forgot-password': typeof LocaleauthForgotPasswordRoute
  '/$locale/otp': typeof LocaleauthOtpRoute
  '/$locale/sign-in': typeof LocaleauthSignInRoute
  '/$locale/sign-in-2': typeof LocaleauthSignIn2Route
  '/$locale/sign-up': typeof LocaleauthSignUpRoute
  '/$locale/401': typeof Localeerrors401Route
  '/$locale/403': typeof Localeerrors403Route
  '/$locale/404': typeof Localeerrors404Route
  '/$locale/500': typeof Localeerrors500Route
  '/$locale/503': typeof Localeerrors503Route
  '/$locale/': typeof LocaleAuthenticatedIndexRoute
  '/$locale/errors/$error': typeof LocaleAuthenticatedErrorsErrorRoute
  '/$locale/settings/account': typeof LocaleAuthenticatedSettingsAccountRoute
  '/$locale/settings/appearance': typeof LocaleAuthenticatedSettingsAppearanceRoute
  '/$locale/settings/display': typeof LocaleAuthenticatedSettingsDisplayRoute
  '/$locale/settings/notifications': typeof LocaleAuthenticatedSettingsNotificationsRoute
  '/$locale/apps/': typeof LocaleAuthenticatedAppsIndexRoute
  '/$locale/chats/': typeof LocaleAuthenticatedChatsIndexRoute
  '/$locale/help-center/': typeof LocaleAuthenticatedHelpCenterIndexRoute
  '/$locale/settings/': typeof LocaleAuthenticatedSettingsIndexRoute
  '/$locale/tasks/': typeof LocaleAuthenticatedTasksIndexRoute
  '/$locale/users/': typeof LocaleAuthenticatedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleAuthenticatedIndexRoute
  '/$locale/forgot-password': typeof LocaleauthForgotPasswordRoute
  '/$locale/otp': typeof LocaleauthOtpRoute
  '/$locale/sign-in': typeof LocaleauthSignInRoute
  '/$locale/sign-in-2': typeof LocaleauthSignIn2Route
  '/$locale/sign-up': typeof LocaleauthSignUpRoute
  '/$locale/401': typeof Localeerrors401Route
  '/$locale/403': typeof Localeerrors403Route
  '/$locale/404': typeof Localeerrors404Route
  '/$locale/500': typeof Localeerrors500Route
  '/$locale/503': typeof Localeerrors503Route
  '/$locale/errors/$error': typeof LocaleAuthenticatedErrorsErrorRoute
  '/$locale/settings/account': typeof LocaleAuthenticatedSettingsAccountRoute
  '/$locale/settings/appearance': typeof LocaleAuthenticatedSettingsAppearanceRoute
  '/$locale/settings/display': typeof LocaleAuthenticatedSettingsDisplayRoute
  '/$locale/settings/notifications': typeof LocaleAuthenticatedSettingsNotificationsRoute
  '/$locale/apps': typeof LocaleAuthenticatedAppsIndexRoute
  '/$locale/chats': typeof LocaleAuthenticatedChatsIndexRoute
  '/$locale/help-center': typeof LocaleAuthenticatedHelpCenterIndexRoute
  '/$locale/settings': typeof LocaleAuthenticatedSettingsIndexRoute
  '/$locale/tasks': typeof LocaleAuthenticatedTasksIndexRoute
  '/$locale/users': typeof LocaleAuthenticatedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/_authenticated': typeof LocaleAuthenticatedRouteRouteWithChildren
  '/$locale/_authenticated/settings': typeof LocaleAuthenticatedSettingsRouteRouteWithChildren
  '/$locale/(auth)/forgot-password': typeof LocaleauthForgotPasswordRoute
  '/$locale/(auth)/otp': typeof LocaleauthOtpRoute
  '/$locale/(auth)/sign-in': typeof LocaleauthSignInRoute
  '/$locale/(auth)/sign-in-2': typeof LocaleauthSignIn2Route
  '/$locale/(auth)/sign-up': typeof LocaleauthSignUpRoute
  '/$locale/(errors)/401': typeof Localeerrors401Route
  '/$locale/(errors)/403': typeof Localeerrors403Route
  '/$locale/(errors)/404': typeof Localeerrors404Route
  '/$locale/(errors)/500': typeof Localeerrors500Route
  '/$locale/(errors)/503': typeof Localeerrors503Route
  '/$locale/_authenticated/': typeof LocaleAuthenticatedIndexRoute
  '/$locale/_authenticated/errors/$error': typeof LocaleAuthenticatedErrorsErrorRoute
  '/$locale/_authenticated/settings/account': typeof LocaleAuthenticatedSettingsAccountRoute
  '/$locale/_authenticated/settings/appearance': typeof LocaleAuthenticatedSettingsAppearanceRoute
  '/$locale/_authenticated/settings/display': typeof LocaleAuthenticatedSettingsDisplayRoute
  '/$locale/_authenticated/settings/notifications': typeof LocaleAuthenticatedSettingsNotificationsRoute
  '/$locale/_authenticated/apps/': typeof LocaleAuthenticatedAppsIndexRoute
  '/$locale/_authenticated/chats/': typeof LocaleAuthenticatedChatsIndexRoute
  '/$locale/_authenticated/help-center/': typeof LocaleAuthenticatedHelpCenterIndexRoute
  '/$locale/_authenticated/settings/': typeof LocaleAuthenticatedSettingsIndexRoute
  '/$locale/_authenticated/tasks/': typeof LocaleAuthenticatedTasksIndexRoute
  '/$locale/_authenticated/users/': typeof LocaleAuthenticatedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/settings'
    | '/$locale/forgot-password'
    | '/$locale/otp'
    | '/$locale/sign-in'
    | '/$locale/sign-in-2'
    | '/$locale/sign-up'
    | '/$locale/401'
    | '/$locale/403'
    | '/$locale/404'
    | '/$locale/500'
    | '/$locale/503'
    | '/$locale/'
    | '/$locale/errors/$error'
    | '/$locale/settings/account'
    | '/$locale/settings/appearance'
    | '/$locale/settings/display'
    | '/$locale/settings/notifications'
    | '/$locale/apps/'
    | '/$locale/chats/'
    | '/$locale/help-center/'
    | '/$locale/settings/'
    | '/$locale/tasks/'
    | '/$locale/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/$locale/forgot-password'
    | '/$locale/otp'
    | '/$locale/sign-in'
    | '/$locale/sign-in-2'
    | '/$locale/sign-up'
    | '/$locale/401'
    | '/$locale/403'
    | '/$locale/404'
    | '/$locale/500'
    | '/$locale/503'
    | '/$locale/errors/$error'
    | '/$locale/settings/account'
    | '/$locale/settings/appearance'
    | '/$locale/settings/display'
    | '/$locale/settings/notifications'
    | '/$locale/apps'
    | '/$locale/chats'
    | '/$locale/help-center'
    | '/$locale/settings'
    | '/$locale/tasks'
    | '/$locale/users'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/_authenticated'
    | '/$locale/_authenticated/settings'
    | '/$locale/(auth)/forgot-password'
    | '/$locale/(auth)/otp'
    | '/$locale/(auth)/sign-in'
    | '/$locale/(auth)/sign-in-2'
    | '/$locale/(auth)/sign-up'
    | '/$locale/(errors)/401'
    | '/$locale/(errors)/403'
    | '/$locale/(errors)/404'
    | '/$locale/(errors)/500'
    | '/$locale/(errors)/503'
    | '/$locale/_authenticated/'
    | '/$locale/_authenticated/errors/$error'
    | '/$locale/_authenticated/settings/account'
    | '/$locale/_authenticated/settings/appearance'
    | '/$locale/_authenticated/settings/display'
    | '/$locale/_authenticated/settings/notifications'
    | '/$locale/_authenticated/apps/'
    | '/$locale/_authenticated/chats/'
    | '/$locale/_authenticated/help-center/'
    | '/$locale/_authenticated/settings/'
    | '/$locale/_authenticated/tasks/'
    | '/$locale/_authenticated/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/_authenticated': {
      id: '/$locale/_authenticated'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleAuthenticatedRouteRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/_authenticated/': {
      id: '/$locale/_authenticated/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleAuthenticatedIndexRouteImport
      parentRoute: typeof LocaleAuthenticatedRouteRoute
    }
    '/$locale/(errors)/503': {
      id: '/$locale/(errors)/503'
      path: '/503'
      fullPath: '/$locale/503'
      preLoaderRoute: typeof Localeerrors503RouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/(errors)/500': {
      id: '/$locale/(errors)/500'
      path: '/500'
      fullPath: '/$locale/500'
      preLoaderRoute: typeof Localeerrors500RouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/(errors)/404': {
      id: '/$locale/(errors)/404'
      path: '/404'
      fullPath: '/$locale/404'
      preLoaderRoute: typeof Localeerrors404RouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/(errors)/403': {
      id: '/$locale/(errors)/403'
      path: '/403'
      fullPath: '/$locale/403'
      preLoaderRoute: typeof Localeerrors403RouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/(errors)/401': {
      id: '/$locale/(errors)/401'
      path: '/401'
      fullPath: '/$locale/401'
      preLoaderRoute: typeof Localeerrors401RouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/(auth)/sign-up': {
      id: '/$locale/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/$locale/sign-up'
      preLoaderRoute: typeof LocaleauthSignUpRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/(auth)/sign-in-2': {
      id: '/$locale/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/$locale/sign-in-2'
      preLoaderRoute: typeof LocaleauthSignIn2RouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/(auth)/sign-in': {
      id: '/$locale/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/$locale/sign-in'
      preLoaderRoute: typeof LocaleauthSignInRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/(auth)/otp': {
      id: '/$locale/(auth)/otp'
      path: '/otp'
      fullPath: '/$locale/otp'
      preLoaderRoute: typeof LocaleauthOtpRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/(auth)/forgot-password': {
      id: '/$locale/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/$locale/forgot-password'
      preLoaderRoute: typeof LocaleauthForgotPasswordRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/_authenticated/settings': {
      id: '/$locale/_authenticated/settings'
      path: '/settings'
      fullPath: '/$locale/settings'
      preLoaderRoute: typeof LocaleAuthenticatedSettingsRouteRouteImport
      parentRoute: typeof LocaleAuthenticatedRouteRoute
    }
    '/$locale/_authenticated/users/': {
      id: '/$locale/_authenticated/users/'
      path: '/users'
      fullPath: '/$locale/users/'
      preLoaderRoute: typeof LocaleAuthenticatedUsersIndexRouteImport
      parentRoute: typeof LocaleAuthenticatedRouteRoute
    }
    '/$locale/_authenticated/tasks/': {
      id: '/$locale/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/$locale/tasks/'
      preLoaderRoute: typeof LocaleAuthenticatedTasksIndexRouteImport
      parentRoute: typeof LocaleAuthenticatedRouteRoute
    }
    '/$locale/_authenticated/settings/': {
      id: '/$locale/_authenticated/settings/'
      path: '/'
      fullPath: '/$locale/settings/'
      preLoaderRoute: typeof LocaleAuthenticatedSettingsIndexRouteImport
      parentRoute: typeof LocaleAuthenticatedSettingsRouteRoute
    }
    '/$locale/_authenticated/help-center/': {
      id: '/$locale/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/$locale/help-center/'
      preLoaderRoute: typeof LocaleAuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof LocaleAuthenticatedRouteRoute
    }
    '/$locale/_authenticated/chats/': {
      id: '/$locale/_authenticated/chats/'
      path: '/chats'
      fullPath: '/$locale/chats/'
      preLoaderRoute: typeof LocaleAuthenticatedChatsIndexRouteImport
      parentRoute: typeof LocaleAuthenticatedRouteRoute
    }
    '/$locale/_authenticated/apps/': {
      id: '/$locale/_authenticated/apps/'
      path: '/apps'
      fullPath: '/$locale/apps/'
      preLoaderRoute: typeof LocaleAuthenticatedAppsIndexRouteImport
      parentRoute: typeof LocaleAuthenticatedRouteRoute
    }
    '/$locale/_authenticated/settings/notifications': {
      id: '/$locale/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/$locale/settings/notifications'
      preLoaderRoute: typeof LocaleAuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof LocaleAuthenticatedSettingsRouteRoute
    }
    '/$locale/_authenticated/settings/display': {
      id: '/$locale/_authenticated/settings/display'
      path: '/display'
      fullPath: '/$locale/settings/display'
      preLoaderRoute: typeof LocaleAuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof LocaleAuthenticatedSettingsRouteRoute
    }
    '/$locale/_authenticated/settings/appearance': {
      id: '/$locale/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/$locale/settings/appearance'
      preLoaderRoute: typeof LocaleAuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof LocaleAuthenticatedSettingsRouteRoute
    }
    '/$locale/_authenticated/settings/account': {
      id: '/$locale/_authenticated/settings/account'
      path: '/account'
      fullPath: '/$locale/settings/account'
      preLoaderRoute: typeof LocaleAuthenticatedSettingsAccountRouteImport
      parentRoute: typeof LocaleAuthenticatedSettingsRouteRoute
    }
    '/$locale/_authenticated/errors/$error': {
      id: '/$locale/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/$locale/errors/$error'
      preLoaderRoute: typeof LocaleAuthenticatedErrorsErrorRouteImport
      parentRoute: typeof LocaleAuthenticatedRouteRoute
    }
  }
}

interface LocaleAuthenticatedSettingsRouteRouteChildren {
  LocaleAuthenticatedSettingsAccountRoute: typeof LocaleAuthenticatedSettingsAccountRoute
  LocaleAuthenticatedSettingsAppearanceRoute: typeof LocaleAuthenticatedSettingsAppearanceRoute
  LocaleAuthenticatedSettingsDisplayRoute: typeof LocaleAuthenticatedSettingsDisplayRoute
  LocaleAuthenticatedSettingsNotificationsRoute: typeof LocaleAuthenticatedSettingsNotificationsRoute
  LocaleAuthenticatedSettingsIndexRoute: typeof LocaleAuthenticatedSettingsIndexRoute
}

const LocaleAuthenticatedSettingsRouteRouteChildren: LocaleAuthenticatedSettingsRouteRouteChildren =
  {
    LocaleAuthenticatedSettingsAccountRoute:
      LocaleAuthenticatedSettingsAccountRoute,
    LocaleAuthenticatedSettingsAppearanceRoute:
      LocaleAuthenticatedSettingsAppearanceRoute,
    LocaleAuthenticatedSettingsDisplayRoute:
      LocaleAuthenticatedSettingsDisplayRoute,
    LocaleAuthenticatedSettingsNotificationsRoute:
      LocaleAuthenticatedSettingsNotificationsRoute,
    LocaleAuthenticatedSettingsIndexRoute:
      LocaleAuthenticatedSettingsIndexRoute,
  }

const LocaleAuthenticatedSettingsRouteRouteWithChildren =
  LocaleAuthenticatedSettingsRouteRoute._addFileChildren(
    LocaleAuthenticatedSettingsRouteRouteChildren,
  )

interface LocaleAuthenticatedRouteRouteChildren {
  LocaleAuthenticatedSettingsRouteRoute: typeof LocaleAuthenticatedSettingsRouteRouteWithChildren
  LocaleAuthenticatedIndexRoute: typeof LocaleAuthenticatedIndexRoute
  LocaleAuthenticatedErrorsErrorRoute: typeof LocaleAuthenticatedErrorsErrorRoute
  LocaleAuthenticatedAppsIndexRoute: typeof LocaleAuthenticatedAppsIndexRoute
  LocaleAuthenticatedChatsIndexRoute: typeof LocaleAuthenticatedChatsIndexRoute
  LocaleAuthenticatedHelpCenterIndexRoute: typeof LocaleAuthenticatedHelpCenterIndexRoute
  LocaleAuthenticatedTasksIndexRoute: typeof LocaleAuthenticatedTasksIndexRoute
  LocaleAuthenticatedUsersIndexRoute: typeof LocaleAuthenticatedUsersIndexRoute
}

const LocaleAuthenticatedRouteRouteChildren: LocaleAuthenticatedRouteRouteChildren =
  {
    LocaleAuthenticatedSettingsRouteRoute:
      LocaleAuthenticatedSettingsRouteRouteWithChildren,
    LocaleAuthenticatedIndexRoute: LocaleAuthenticatedIndexRoute,
    LocaleAuthenticatedErrorsErrorRoute: LocaleAuthenticatedErrorsErrorRoute,
    LocaleAuthenticatedAppsIndexRoute: LocaleAuthenticatedAppsIndexRoute,
    LocaleAuthenticatedChatsIndexRoute: LocaleAuthenticatedChatsIndexRoute,
    LocaleAuthenticatedHelpCenterIndexRoute:
      LocaleAuthenticatedHelpCenterIndexRoute,
    LocaleAuthenticatedTasksIndexRoute: LocaleAuthenticatedTasksIndexRoute,
    LocaleAuthenticatedUsersIndexRoute: LocaleAuthenticatedUsersIndexRoute,
  }

const LocaleAuthenticatedRouteRouteWithChildren =
  LocaleAuthenticatedRouteRoute._addFileChildren(
    LocaleAuthenticatedRouteRouteChildren,
  )

interface LocaleRouteRouteChildren {
  LocaleAuthenticatedRouteRoute: typeof LocaleAuthenticatedRouteRouteWithChildren
  LocaleauthForgotPasswordRoute: typeof LocaleauthForgotPasswordRoute
  LocaleauthOtpRoute: typeof LocaleauthOtpRoute
  LocaleauthSignInRoute: typeof LocaleauthSignInRoute
  LocaleauthSignIn2Route: typeof LocaleauthSignIn2Route
  LocaleauthSignUpRoute: typeof LocaleauthSignUpRoute
  Localeerrors401Route: typeof Localeerrors401Route
  Localeerrors403Route: typeof Localeerrors403Route
  Localeerrors404Route: typeof Localeerrors404Route
  Localeerrors500Route: typeof Localeerrors500Route
  Localeerrors503Route: typeof Localeerrors503Route
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleAuthenticatedRouteRoute: LocaleAuthenticatedRouteRouteWithChildren,
  LocaleauthForgotPasswordRoute: LocaleauthForgotPasswordRoute,
  LocaleauthOtpRoute: LocaleauthOtpRoute,
  LocaleauthSignInRoute: LocaleauthSignInRoute,
  LocaleauthSignIn2Route: LocaleauthSignIn2Route,
  LocaleauthSignUpRoute: LocaleauthSignUpRoute,
  Localeerrors401Route: Localeerrors401Route,
  Localeerrors403Route: Localeerrors403Route,
  Localeerrors404Route: Localeerrors404Route,
  Localeerrors500Route: Localeerrors500Route,
  Localeerrors503Route: Localeerrors503Route,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
