import { ValidationPipe } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { SwaggerModule, DocumentBuilder } from '@nestjs/swagger';
import * as Helmet from 'helmet';
import * as Compression from 'compression';
import * as BodyParser from 'body-parser';
import { AppModule } from '@/app/app.module';
import { APP } from '@/app/app.config';
import { HttpExceptionFilter } from '@/common/filters/http-exception.filter';
import { ErrorsInterceptor } from '@/common/interceptors/exception.interceptor.ts';
import { LoggingInterceptor } from '@/common/interceptors/logging.interceptor';
// import { TransformInterceptor } from '@/common/interceptors/transform.interceptor';
