/*
 * Auto-generated by `openapi-typescript`.
 * Run: `bun run openapi:generate` after setting $OPENAPI_SCHEMA_URL
 */

// biome-ignore lint/complexity/noBannedTypes: This is auto-generated code.
export type paths = {};
