export interface ICountry {
  name: string;
  alpha2: string;
  alpha3: string | null;
  numeric: string | null;
  phone: string | null;
  lang: string | null;
  langs: string[];
}

const countries: ICountry[] = [
  {
    name: 'Andorra',
    alpha2: 'AD',
    alpha3: 'AND',
    numeric: '020',
    phone: '+376',
    lang: 'ca',
    langs: ['ca'],
  },
  {
    name: 'United Arab Emirates',
    alpha2: 'AE',
    alpha3: 'ARE',
    numeric: '784',
    phone: '+971',
    lang: 'ar',
    langs: ['ar'],
  },
  {
    name: 'African Union',
    alpha2: 'AFRUN',
    alpha3: null,
    numeric: null,
    phone: null,
    lang: null,
    langs: [],
  },
  {
    name: 'Antigua and Barbuda',
    alpha2: 'AG',
    alpha3: 'ATG',
    numeric: '028',
    phone: '+1-268',
    lang: 'en',
    langs: ['en'],
  },
  {
    name: 'Anguilla',
    alpha2: 'AI',
    alpha3: 'AIA',
    numeric: '660',
    phone: '+1-264',
    lang: 'en',
    langs: ['en'],
  },
  {
    name: 'Albania',
    alpha2: 'AL',
    alpha3: 'ALB',
    numeric: '008',
    phone: '+355',
    lang: 'sq',
    langs: ['sq'],
  },
  {
    name: 'Armenia',
    alpha2: 'AM',
    alpha3: 'ARM',
    numeric: '051',
    phone: '+374',
    lang: 'hy',
    langs: ['hy'],
  },
  {
    name: 'Amsterdam',
    alpha2: 'AMS',
    alpha3: null,
    numeric: null,
    phone: null,
    lang: null,
    langs: [],
  },
  {
    name: 'Angola',
    alpha2: 'AO',
    alpha3: 'AGO',
    numeric: '024',
    phone: '+244',
    lang: 'pt',
    langs: ['pt'],
  },
  {
    name: 'Antarctica',
    alpha2: 'AQ',
    alpha3: 'ATA',
    numeric: '010',
    phone: '+672',
    lang: 'en',
    langs: ['en'],
  },
  {
    name: 'Argentina',
    alpha2: 'AR',
    alpha3: 'ARG',
    numeric: '032',
    phone: '+54',
    lang: 'es',
    langs: ['es'],
  },
  {
    name: 'American Samoa',
    alpha2: 'AS',
    alpha3: 'ASM',
    numeric: '016',
    phone: '+1-684',
    lang: 'en',
    langs: ['en'],
  },
  {
    name: 'Austria',
    alpha2: 'AT',
    alpha3: 'AUT',
    numeric: '040',
    phone: '+43',
    lang: 'de',
    langs: ['de'],
  },
  {
    name: 'Australia',
    alpha2: 'AU',
    alpha3: 'AUS',
    numeric: '016',
    phone: '+61',
    lang: 'en',
    langs: ['en'],
  },
  {
    name: 'Aruba',
    alpha2: 'AW',
    alpha3: 'ABW',
    numeric: '533',
    phone: '+297',
    lang: 'nl',
    langs: ['nl'],
  },
  {
    name: 'Åland Islands',
    alpha2: 'AX',
    alpha3: 'ALA',
    numeric: '248',
    phone: '+358',
    lang: 'sv',
    langs: ['sv'],
  },
  {
    name: 'Azerbaijan',
    alpha2: 'AZ',
    alpha3: 'AZE',
    numeric: '031',
    phone: '+994',
    lang: 'az',
    langs: ['az'],
  },
  {
    name: 'Bosnia and Herzegovina',
    alpha2: 'BA',
    alpha3: 'BIH',
    numeric: '070',
    phone: '+387',
    lang: 'bs',
    langs: ['bs'],
  },
  {
    name: 'Barbados',
    alpha2: 'BB',
    alpha3: 'BRB',
    numeric: '052',
    phone: '+1-246',
    lang: 'en',
