export interface ICountry {
  name: string;
  alpha2: string;
  alpha3: string | null;
  numeric: string | null;
  phone: string | null;
  lang: string | null;
  langs: string[];
}

const countries: ICountry[] = [
  {
    name: 'Andorra',
    alpha2: 'AD',
    alpha3: 'AND',
    numeric: '020',
    phone: '+376',
    lang: 'ca',
    langs: ['ca'],
  },
  {
    name: 'United Arab Emirates',
    alpha2: 'AE',
    alpha3: 'ARE',
    numeric: '784',
    phone: '+971',
    lang: 'ar',
    langs: ['ar'],
  },
  {
    name: 'African Union',
    alpha2: 'AFRUN',
    alpha3: null,
    numeric: null,
    phone: null,
    lang: null,
    langs: [],
  },
  {
    name: 'Antigua and Barbuda',
    alpha2: 'AG',
    alpha3: 'ATG',
    numeric: '028',
    phone: '+1-268',
    lang: 'en',
    langs: ['en'],
  },
  {
    name: 'Anguilla',
    alpha2: 'AI',
    alpha3: 'AIA',
    numeric: '660',
    phone: '+1-264',
    lang: 'en',
    langs: ['en'],
  },
  {
    name: 'Albania',
    alpha2: 'AL',
    alpha3: 'ALB',
    numeric: '008',
    phone: '+355',
    lang: 'sq',
    langs: ['sq'],
  },
  {
    name: 'Armenia',
    alpha2: 'AM',
    alpha3: 'ARM',
    numeric: '051',
    phone: '+374',
    lang: 'hy',
    langs: ['hy'],
  },
  {
    name: 'Amsterdam',
    alpha2: 'AMS',
    alpha3: null,
    numeric: null,
    phone: null,
    lang: null,
    langs: [],
  },
  {
    name: 'Angola',
    alpha2: 'AO',
    alpha3: 'AGO',
    numeric: '024',
    phone: '+244',
    lang: 'pt',
    langs: ['pt'],
  },
  {
    name: 'Antarctica',
    alpha2: 'AQ',
    alpha3: 'ATA',
    numeric: '010',
    phone: '+672',
    lang: 'en',
    langs: ['en'],
  },
  {
    name: 'Argentina',
    alpha2: 'AR',
    alpha3: 'ARG',
    numeric: '032',
    phone: '+54',
    lang: 'es',
    langs: ['es'],
  },
  {
    name: 'American Samoa',
    alpha2: 'AS',
    alpha3: 'ASM',
    numeric: '016',
    phone: '+1-684',
    lang: 'en',
    langs: ['en'],
  },
  {
    name: 'Austria',
    alpha2: 'AT',
    alpha3: 'AUT',
    numeric: '040',
    phone: '+43',
    lang: 'de',
    langs: ['de'],
  },
  {
    name: 'Australia',
    alpha2: 'AU',
    alpha3: 'AUS',
    numeric: '016',
    phone: '+61',
    lang: 'en',
    langs: ['en'],
  },
  {
    name: 'Aruba',
    alpha2: 'AW',
    alpha3: 'ABW',
    numeric: '533',
    phone: '+297',
    lang: 'nl',
    langs: ['nl'],
  },
  {
    name: 'Åland Islands',
    alpha2: 'AX',
    alpha3: 'ALA',
    numeric: '248',
    phone: '+358',
    lang: 'sv',
    langs: ['sv'],
  },
  {
    name: 'Azerbaijan',
    alpha2: 'AZ',
    alpha3: 'AZE',
    numeric: '031',
    phone: '+994',
    lang: 'az',
    langs: ['az'],
  },
  {
    name: 'Bosnia and Herzegovina',
    alpha2: 'BA',
    alpha3: 'BIH',
    numeric: '070',
    phone: '+387',
    lang: 'bs',
    langs: ['bs'],
  },
  {
    name: 'Barbados',
    alpha2: 'BB',
    alpha3: 'BRB',
    numeric: '052',
    phone: '+1-246',
    lang: 'en',
    langs: ['en'],
  },
  {
    name: 'Bangladesh',
    alpha2: 'BD',
    alpha3: 'BGD',
    numeric: '050',
    phone: '+880',
    lang: 'bn',
    langs: ['bn', 'en'],
  },
  {
    name: 'Belgium',
    alpha2: 'BE',
    alpha3: 'BEL',
    numeric: '056',
    phone: '+32',
    lang: 'nl',
    langs: ['nl', 'fr', 'de'],
  },
  {
    name: 'Burkina Faso',
    alpha2: 'BF',
    alpha3: 'BFA',
    numeric: '854',
    phone: '+226',
    lang: 'fr',
    langs: ['fr'],
  },
  {
    name: 'Bulgaria',
    alpha2: 'BG',
    alpha3: 'BGR',
    numeric: '100',
    phone: '+359',
    lang: 'bg',
    langs: ['bg'],
  },
  {
    name: 'Bahrain',
    alpha2: 'BH',
    alpha3: 'BHR',
    numeric: '048',
    phone: '+973',
    lang: 'ar',
    langs: ['ar'],
  },
  {
    name: 'Burundi',
    alpha2: 'BI',
    alpha3: 'BDI',
    numeric: '108',
    phone: '+257',
    lang: 'fr',
    langs: ['fr', 'rn', 'en'],
  },
  {
    name: 'Benin',
    alpha2: 'BJ',
    alpha3: 'BEN',
    numeric: '204',
    phone: '+229',
    lang: 'fr',
    langs: ['fr'],
  },
  {
    name: 'Saint Barthélemy',
    alpha2: 'BL',
    alpha3: 'BLM',
    numeric: '652',
    phone: '+590',
    lang: 'fr',
    langs: ['fr'],
  },
  {
    name: 'Bermuda',
    alpha2: 'BM',
    alpha3: 'BMU',
    numeric: '060',
    phone: '+1-441',
    lang: 'en',
    langs: ['en'],
  },
  {
    name: 'Brunei',
    alpha2: 'BN',
    alpha3: 'BRN',
    numeric: '096',
    phone: '+673',
    lang: 'ms',
    langs: ['ms', 'en'],
  },
  {
    name: 'Bolivia',
    alpha2: 'BO',
    alpha3: 'BOL',
    numeric: '068',
    phone: '+591',
    lang: 'es',
    langs: ['es', 'ay', 'qu'],
  },
  {
    name: 'Bonaire',
    alpha2: 'BQ-BO',
    alpha3: 'BES',
    numeric: '535',
    phone: '+599',
    lang: 'nl',
    langs: ['nl'],
  },
  {
    name: 'Saba',
    alpha2: 'BQ-SA',
    alpha3: null,
    numeric: null,
    phone: null,
    lang: null,
    langs: [],
  },
  {
    name: 'Sint Eustatius',
    alpha2: 'BQ-SE',
    alpha3: null,
    numeric: null,
    phone: null,
    lang: null,
    langs: [],
  },
  {
    name: 'Brazil',
    alpha2: 'BR',
    alpha3: 'BRA',
    numeric: '076',
    phone: '+55',
    lang: 'pt',
    langs: ['pt'],
  },
  {
    name: 'Bahamas',
    alpha2: 'BS',
    alpha3: 'BHS',
    numeric: '044',
    phone: '+1-242',
    lang: 'en',
    langs: ['en'],
  },
  {
    name: 'Bhutan',
    alpha2: 'BT',
    alpha3: 'BTN',
    numeric: '064',
    phone: '+975',
    lang: 'dz',
    langs: ['dz'],
  },
  {
    name: 'Botswana',
    alpha2: 'BW',
    alpha3: 'BWA',
    numeric: '072',
    phone: '+267',
    lang: 'en',
    langs: ['en', 'tn'],
  },
  {
    name: 'Belarus',
    alpha2: 'BY',
    alpha3: 'BLR',
    numeric: '112',
    phone: '+375',
    lang: 'be',
    langs: ['be', 'ru'],
  },
  {
    name: 'Belize',
    alpha2: 'BZ',
    alpha3: 'BLZ',
    numeric: '084',
    phone: '+501',
    lang: 'en',
