export interface ICountry {
  name: string;
  alpha2: string;
  alpha3: string | null;
  numeric: string | null;
  phone: string | null;
  lang: string | null;
  langs: string[];
}

const countries: ICountry[] = [
  {
    name: 'Andorra',
    alpha2: 'AD',
    alpha3: 'AND',
    numeric: '020',
    phone: '+376',
    lang: 'ca',
    langs: ['ca'],
  },
  {
    name: 'United Arab Emirates',
    alpha2: 'AE',
    alpha3: 'ARE',
    numeric: '784',
    phone: '+971',
    lang: 'ar',
    langs: ['ar'],
  },
  {
    name: 'African Union',
    alpha2: 'AFRUN',
    alpha3: null,
    numeric: null,
    phone: null,
    lang: null,
    langs: [],
  },
  {
    name: 'Antigua and Barbuda',
    alpha2: 'AG',
    alpha3: 'ATG',
    numeric: '028',
    phone: '+1-268',
    lang: 'en',
    langs: ['en'],
  },
  {
    name: 'Anguilla',
    alpha2: 'AI',
    alpha3: 'AIA',
    numeric: '660',
    phone: '+1-264',
    lang: 'en',
    langs: ['en'],
  },
  {
    name: 'Albania',
    alpha2: 'AL',
    alpha3: 'ALB',
    numeric: '008',
    phone: '+355',
    lang: 'sq',
    langs: ['sq'],
  },
  {
    name: 'Armenia',
    alpha2: 'AM',
    alpha3: 'ARM',
    numeric: '051',
    phone: '+374',
    lang: 'hy',
    langs: ['hy'],
  },
  {
    name: 'Amsterdam',
    alpha2: 'AMS',
    alpha3: null,
    numeric: null,
    phone: null,
    lang: null,
    langs: [],
  },
  {
    name: 'Angola',
    alpha2: 'AO',
    alpha3: 'AGO',
    numeric: '024',
    phone: '+244',
    lang: 'pt',
    langs: ['pt'],
  },
  {
    name: 'Antarctica',
    alpha2: 'AQ',
    alpha3: 'ATA',
    numeric: '010',
    phone: '+672',
    lang: 'en',
    langs: ['en'],
  },
  {
    name: 'Argentina',
    alpha2: 'AR',
    alpha3: 'ARG',
    numeric: '032',
    phone: '+54',
    lang: 'es',
    langs: ['es'],
  },
  {
    name: 'American Samoa',
    alpha2: 'AS',
    alpha3: 'ASM',
    numeric: '016',
    phone: '+1-684',
    lang: 'en',
    langs: ['en'],
  },
  {
    name: 'Austria',
    alpha2: 'AT',
    alpha3: 'AUT',
    numeric: '040',
    phone: '+43',
    lang: 'de',
    langs: ['de'],
  },
  {
    name: 'Australia',
    alpha2: 'AU',
    alpha3: 'AUS',
    numeric: '016',
    phone: '+61',
    lang: 'en',
    langs: ['en'],
  },
  {
    name: 'Aruba',
    alpha2: 'AW',
    alpha3: 'ABW',
    numeric: '533',
    phone: '+297',
    lang: 'nl',
    langs: ['nl'],
  },
  {
    name: 'Åland Islands',
    alpha2: 'AX',
    alpha3: 'ALA',
    numeric: '248',
    phone: '+358',
    lang: 'sv',
    langs: ['sv'],
  },
  {
    name: 'Azerbaijan',
    alpha2: 'AZ',
    alpha3: 'AZE',
    numeric: '031',
    phone: '+994',
    lang: 'az',
    langs: ['az'],
  },
  {
    name: 'Bosnia and Herzegovina',
    alpha2: 'BA',
    alpha3: 'BIH',
    numeric: '070',
    phone: '+387',
    lang: 'bs',
    langs: ['bs'],
  },
  {
    name: 'Barbados',
    alpha2: 'BB',
    alpha3: 'BRB',
    numeric: '052',
    phone: '+1-246',
    lang: 'en',
    langs: ['en'],
  },
  {
    name: 'Bangladesh',
    alpha2: 'BD',
    alpha3: 'BGD',
    numeric: '050',
    phone: '+880',
    lang: 'bn',
    langs: ['bn', 'en'],
  },
  {
    name: 'Belgium',
    alpha2: 'BE',
    alpha3: 'BEL',
    numeric: '056',
    phone: '+32',
    lang: 'nl',
    langs: ['nl', 'fr', 'de'],
  },
  {
    name: 'Burkina Faso',
    alpha2: 'BF',
    alpha3: 'BFA',
    numeric: '854',
    phone: '+226',
    lang: 'fr',
    langs: ['fr'],
  },
  {
    name: 'Bulgaria',
    alpha2: 'BG',
    alpha3: 'BGR',
    numeric: '100',
    phone: '+359',
    lang: 'bg',
    langs: ['bg'],
  },
  {
    name: 'Bahrain',
    alpha2: 'BH',
    alpha3: 'BHR',
    numeric: '048',
    phone: '+973',
    lang: 'ar',
    langs: ['ar'],
  },
  {
    name: 'Burundi',
    alpha2: 'BI',
    alpha3: 'BDI',
    numeric: '108',
    phone: '+257',
    lang: 'fr',
    langs: ['fr', 'rn', 'en'],
  },
  {
    name: 'Benin',
    alpha2: 'BJ',
    alpha3: 'BEN',
    numeric: '204',
    phone: '+229',
    lang: 'fr',
    langs: ['fr'],
  },
  {
    name: 'Saint Barthélemy',
    alpha2: 'BL',
    alpha3: 'BLM',
    numeric: '652',
    phone: '+590',
    lang: 'fr',
    langs: ['fr'],
  },
  {
    name: 'Bermuda',
    alpha2: 'BM',
    alpha3: 'BMU',
    numeric: '060',
    phone: '+1-441',
    lang: 'en',
    langs: ['en'],
  },
  {
    name: 'Brunei',
    alpha2: 'BN',
    alpha3: 'BRN',
    numeric: '096',
    phone: '+673',
    lang: 'ms',
    langs: ['ms', 'en'],
  },
  {
    name: 'Bolivia',
    alpha2: 'BO',
    alpha3: 'BOL',
    numeric: '068',
    phone: '+591',
    lang: 'es',
    langs: ['es', 'ay', 'qu'],
  },
  {
    name: 'Bonaire',
    alpha2: 'BQ-BO',
    alpha3: 'BES',
    numeric: '535',
    phone: '+599',
    lang: 'nl',
    langs: ['nl'],
  },
  {
    name: 'Saba',
    alpha2: 'BQ-SA',
    alpha3: null,
    numeric: null,
    phone: null,
    lang: null,
    langs: [],
  },
  {
    name: 'Sint Eustatius',
    alpha2: 'BQ-SE',
    alpha3: null,
    numeric: null,
    phone: null,
    lang: null,
    langs: [],
  },
  {
    name: 'Brazil',
    alpha2: 'BR',
    alpha3: 'BRA',
    numeric: '076',
    phone: '+55',
    lang: 'pt',
    langs: ['pt'],
  },
  {
    name: 'Bahamas',
    alpha2: 'BS',
    alpha3: 'BHS',
    numeric: '044',
    phone: '+1-242',
    lang: 'en',
    langs: ['en'],
  },
  {
    name: 'Bhutan',
    alpha2: 'BT',
    alpha3: 'BTN',
    numeric: '064',
    phone: '+975',
    lang: 'dz',
    langs: ['dz'],
  },
  {
    name: 'Botswana',
    alpha2: 'BW',
    alpha3: 'BWA',
    numeric: '072',
    phone: '+267',
    lang: 'en',
    langs: ['en', 'tn'],
  },
  {
    name: 'Belarus',
    alpha2: 'BY',
    alpha3: 'BLR',
    numeric: '112',
    phone: '+375',
    lang: 'be',
    langs: ['be', 'ru'],
  },
  {
    name: 'Belize',
    alpha2: 'BZ',
    alpha3: 'BLZ',
    numeric: '084',
    phone: '+501',
    lang: 'en',
    langs: ['en'],
  },
  {
    name: 'Canada',
    alpha2: 'CA',
    alpha3: 'CAN',
    numeric: '124',
    phone: '+1',
    lang: 'en',
    langs: ['en', 'fr'],
  },
  {
    name: 'Cocos Islands',
    alpha2: 'CC',
    alpha3: 'CCK',
    numeric: '166',
    phone: '+61',
    lang: 'en',
    langs: ['en'],
  },
  {
    name: 'Democratis Republic of Congo',
    alpha2: 'CD',
    alpha3: 'COD',
    numeric: '180',
    phone: '+243',
    lang: 'fr',
    langs: ['fr', 'ln', 'kg', 'sw', 'lu'],
  },
  {
    name: 'Central African Republic',
    alpha2: 'CF',
    alpha3: 'CAF',
    numeric: '140',
    phone: '+236',
    lang: 'fr',
    langs: ['fr', 'sg'],
  },
  {
    name: 'Congo',
    alpha2: 'CG',
    alpha3: 'COG',
    numeric: '178',
    phone: '+242',
    lang: 'fr',
    langs: ['fr'],
  },
  {
    name: 'Switzerland',
    alpha2: 'CH',
    alpha3: 'CHE',
    numeric: '756',
    phone: '+41',
    lang: 'de',
    langs: ['de', 'fr', 'it', 'rm'],
  },
  {
    name: "Côte d'Ivoire",
    alpha2: 'CI',
    alpha3: 'CIV',
    numeric: '384',
    phone: '+225',
    lang: 'fr',
    langs: ['fr'],
  },
  {
    name: 'Cook Island',
    alpha2: 'CK',
    alpha3: 'COK',
    numeric: '184',
    phone: '+682',
    lang: 'en',
    langs: ['en'],
  },
  {
    name: 'Chile',
    alpha2: 'CL',
    alpha3: 'CHL',
    numeric: '152',
    phone: '+56',
    lang: 'es',
    langs: ['es'],
  },
  {
    name: 'Cameroon',
    alpha2: 'CM',
    alpha3: 'CMR',
    numeric: '120',
    phone: '+237',
    lang: 'en',
    langs: ['en', 'fr'],
  },
  {
    name: 'China',
    alpha2: 'CN',
    alpha3: 'CHN',
    numeric: '156',
    phone: '+86',
    lang: 'zh',
    langs: ['zh'],
  },
  {
    name: 'Colombia',
    alpha2: 'CO',
    alpha3: 'COL',
    numeric: '170',
    phone: '+57',
    lang: 'es',
    langs: ['es'],
  },
  {
    name: 'Costa Rica',
    alpha2: 'CR',
    alpha3: 'CRI',
    numeric: '188',
    phone: '+506',
    lang: 'es',
    langs: ['es'],
  },
  {
    name: 'Cuba',
    alpha2: 'CU',
    alpha3: 'CUB',
    numeric: '192',
    phone: '+53',
    lang: 'es',
    langs: ['es'],
  },
  {
    name: 'Cape Verde',
    alpha2: 'CV',
    alpha3: 'CPV',
    numeric: '132',
    phone: '+238',
    lang: 'pt',
    langs: ['pt'],
  },
  {
    name: 'Curaçao',
    alpha2: 'CW',
    alpha3: 'CUW',
    numeric: '531',
    phone: '+599',
    lang: 'nl',
    langs: ['nl'],
  },
  {
    name: 'Christmas Island',
    alpha2: 'CX',
    alpha3: 'CXR',
    numeric: '162',
    phone: '+61',
    lang: 'en',
    langs: ['en', 'ms', 'zh'],
  },
  {
    name: 'Cyprus',
    alpha2: 'CY',
    alpha3: 'CYP',
    numeric: '196',
    phone: '+357',
    lang: 'el',
    langs: ['el', 'tr'],
  },
  {
    name: 'Czech Republic',
    alpha2: 'CZ',
    alpha3: 'CZE',
    numeric: '203',
    phone: '+420',
    lang: 'cs',
    langs: ['cs'],
  },
  {
    name: 'Germany',
    alpha2: 'DE',
    alpha3: 'DEU',
    numeric: '276',
    phone: '+49',
    lang: 'de',
    langs: ['de'],
  },
  {
    name: 'Djibouti',
    alpha2: 'DJ',
    alpha3: 'DJI',
    numeric: '262',
    phone: '+253',
    lang: 'fr',
    langs: ['fr', 'ar'],
  },
  {
    name: 'Denmark',
    alpha2: 'DK',
    alpha3: 'DNK',
    numeric: '208',
    phone: '+45',
    lang: 'da',
    langs: ['da'],
  },
  {
    name: 'Dominica',
    alpha2: 'DM',
    alpha3: 'DMA',
    numeric: '212',
    phone: '+1-767',
    lang: 'en',
    langs: ['en'],
  },
  {
    name: 'Dominican Republic',
    alpha2: 'DO',
    alpha3: 'DOM',
    numeric: '214',
    phone: '+1-809, +1-829, +1-849',
    lang: 'es',
    langs: ['es'],
  },
  {
    name: 'Ecuador',
    alpha2: 'EC',
    alpha3: 'ECU',
    numeric: '218',
    phone: '+593',
    lang: 'es',
    langs: ['es'],
  },
  {
    name: 'Estonia',
    alpha2: 'EE',
    alpha3: 'EST',
    numeric: '233',
    phone: '+372',
    lang: 'et',
    langs: ['et'],
  },
  {
    name: 'Egypt',
    alpha2: 'EG',
    alpha3: 'EGY',
    numeric: '818',
    phone: '+20',
    lang: 'ar',
    langs: ['ar'],
  },
  {
    name: 'Western Sahara',
    alpha2: 'EH',
    alpha3: 'ESH',
    numeric: '732',
    phone: '+212',
    lang: 'ar',
    langs: ['ar'],
  },
  {
    name: 'Eritrea',
    alpha2: 'ER',
    alpha3: 'ERI',
    numeric: '232',
    phone: '+291',
    lang: 'ti',
    langs: ['ti', 'ar', 'en'],
  },
  {
    name: 'Spain',
    alpha2: 'ES',
    alpha3: 'ESP',
    numeric: '724',
    phone: '+34',
    lang: 'es',
    langs: ['es'],
  },
  {
    name: 'Ethiopia',
    alpha2: 'ET',
    alpha3: 'ETH',
    numeric: '231',
    phone: '+251',
    lang: 'am',
    langs: ['am', 'en'],
  },
  {
    name: 'European Union',
    alpha2: 'EU',
    alpha3: null,
    numeric: null,
    phone: null,
    lang: null,
    langs: [],
  },
  {
    name: 'Finland',
    alpha2: 'FI',
    alpha3: 'FIN',
    numeric: '246',
    phone: '+358',
    lang: 'fi',
    langs: ['fi'],
  },
  {
    name: 'Fiji',
    alpha2: 'FJ',
    alpha3: 'FJI',
    numeric: '242',
    phone: '+679',
    lang: 'en',
    langs: ['en'],
  },
  {
    name: 'Falkland Islands',
    alpha2: 'FK',
    alpha3: 'FLK',
    numeric: '238',
    phone: '+500',
    lang: 'en',
    langs: ['en'],
  },
  {
    name: 'Micronesia (Federated States of)',
    alpha2: 'FM',
    alpha3: 'FSM',
    numeric: '583',
    phone: '+691',
    lang: 'en',
    langs: ['en'],
  },
  {
    name: 'Faroe Island',
    alpha2: 'FO',
    alpha3: 'FRO',
    numeric: '234',
    phone: '+298',
    lang: 'fo',
    langs: ['fo'],
  },
  {
    name: 'France',
    alpha2: 'FR',
    alpha3: 'FRA',
    numeric: '250',
    phone: '+33',
    lang: 'fr',
    langs: ['fr'],
  },
  {
    name: 'Gabon',
    alpha2: 'GA',
    alpha3: 'GAB',
    numeric: '266',
    phone: '+241',
    lang: 'fr',
    langs: ['fr'],
  },
  {
    name: 'England',
    alpha2: 'GB-ENG',
    alpha3: null,
    numeric: null,
    phone: null,
    lang: null,
    langs: [],
  },
  {
    name: 'Scotland',
    alpha2: 'GB-SCT',
    alpha3: null,
    numeric: null,
    phone: null,
    lang: null,
    langs: [],
  },
  {
    name: 'United Kingdom',
    alpha2: 'GB-UKM',
    alpha3: 'GBR',
    numeric: '836',
    phone: '+44',
    lang: 'en',
    langs: ['en'],
  },
  {
    name: 'Wales',
    alpha2: 'GB-WLS',
    alpha3: null,
    numeric: null,
    phone: null,
    lang: null,
    langs: [],
  },
  {
    name: 'Northern Ireland',
    alpha2: 'GB-NIR',
    alpha3: null,
    numeric: null,
    phone: null,
    lang: null,
    langs: [],
  },
  {
    name: 'Grenada',
    alpha2: 'GD',
    alpha3: 'GRD',
    numeric: '308',
    phone: '+1-473',
    lang: 'en',
    langs: ['en'],
  },
  {
    name: 'Georgia',
    alpha2: 'GE',
    alpha3: 'GEO',
    numeric: '268',
    phone: '+995',
    lang: 'ka',
    langs: ['ka'],
  },
  {
    name: 'French Guiana',
    alpha2: 'GF',
    alpha3: 'GUF',
